# Generated by Django 6.0.6 on 2026-06-16 06:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات مقاله'),
        ),
    ]
