# Generated by Django 6.0.6 on 2026-06-16 06:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=tinymce.models.HTMLField(),
        ),
    ]
