# Generated by Django 6.0.6 on 2026-06-16 08:34

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='discription',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(default=14, verbose_name='مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(default=15, upload_to='articles/thumbnail/', verbose_name='پوستر مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='short_discription',
            field=models.CharField(default='jkklklklkl', max_length=300, verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
    ]
