# Generated by Django 6.0.6 on 2026-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_discription_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='ssss', max_length=200, unique=True, verbose_name='مسیر url مقاله'),
            preserve_default=False,
        ),
    ]
