# Generated by Django 6.0.6 on 2026-06-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='profile_image',
            new_name='image_article',
        ),
    ]
