# Generated by Django 6.0.6 on 2026-06-12 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_adres_alter_user_profile_image_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی تحویل گیرنده')),
                ('province_city', models.CharField(max_length=100, verbose_name='استان و شهر')),
                ('address', models.CharField(max_length=1000, verbose_name='آدرس')),
                ('address_details', models.CharField(max_length=500, verbose_name='جزئیات آدرس')),
                ('postal_code', models.CharField(max_length=500, verbose_name='کد پستی')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='موبایل تحویل گیرنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
