# Generated by Django 6.0.6 on 2026-06-06 17:01

import django.db.models.deletion
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True, verbose_name='عنوان دسته')),
                ('slug', models.CharField(db_index=True, max_length=80, null=True, unique=True, verbose_name='url دسته')),
                ('chailds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='product.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان محصول')),
                ('discription', models.TextField(max_length=2000, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمیت محصول')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateField(auto_now=True, verbose_name='تاریخ آخرین بروز رسانی')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت محصول')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='مسیر url محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='متن کامنت')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت کامنت')),
                ('star', models.IntegerField(blank=True, default=1, null=True, verbose_name='امتیاز خرید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='static/images/products/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'پرداخت شده'), (2, 'در حال ارسال'), (3, 'ارسال شده'), (4, 'لغو شده')], db_index=True, default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_price', models.IntegerField(verbose_name='کل قیمت')),
                ('note', models.TextField(verbose_name='نکات سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='سفارش دهنده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['create_at', 'status'], name='product_ord_create__0d3d9b_idx'), models.Index(fields=['user', 'status'], name='product_ord_user_id_d645e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_order')],
            },
        ),
    ]
