# Generated by Django 6.0.6 on 2026-06-24 11:28

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_comment_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(db_index=True, default=product.models.generate_number_order, editable=False, null=True),
        ),
    ]
