# Generated by Django 6.0.6 on 2026-06-24 11:29

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_address_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(db_index=True, default=product.models.generate_number_order, editable=False, unique=True),
        ),
    ]
